### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 269: ordinal not in range(128)

### ISSUE THREAD

**Issue by adafnos** [alexhanna/mpeds#16]
When I type python example-lexisnexis.py I receive the following error message:

Added 348 articles, skipped 0 abstracts
Loading vectorizer...
Vectorizing...
Loading classifier...
Predicting...
Loading form vectorizer...
Vectorizing...
Loading form classifier...
Predicting...
example-lexisnexis.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead
See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df_protest['form'] = mobj.getForm(df_protest['TEXT'])
Loading issue vectorizer...
Vectorizing...
Loading issue classifier...
Predicting...
example-lexisnexis.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead
See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df_protest['issue'] = mobj.getIssue(df_protest['TEXT'])
Loading target vectorizer...
Vectorizing...
Loading target classifier...
Predicting...
example-lexisnexis.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead
See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df_protest['target'] = mobj.getTarget(df_protest['TEXT'])
example-lexisnexis.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead
See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df_protest['size'] = mobj.getSize(df_protest['TEXT'])
example-lexisnexis.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead
See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df_protest['smo'] = mobj.getSMO(df_protest['TEXT'])

Traceback (most recent call last):
  File "example-lexisnexis.py", line 38, in <module>
    df_protest['location'] = mobj.getLocation(df_protest['TEXT'])
  File "/src/mpeds/classify_protest.py", line 363, in getLocation
    locations = text.apply(self.location_clf.getLocation, args = [True])
  File "/usr/lib64/python2.7/site-packages/pandas/core/series.py", line 2355, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/_libs/src/inference.pyx", line 1569, in pandas._libs.lib.map_infer (pandas/_libs/lib.c:66440)
  File "/usr/lib64/python2.7/site-packages/pandas/core/series.py", line 2342, in <lambda>
    f = lambda x: func(x, *args, **kwds)
  File "/src/mpeds/open_ended_coders.py", line 352, in getLocation
    cliff_results = self._getCLIFF(text)
  File "/src/mpeds/open_ended_coders.py", line 434, in _getCLIFF
    data = self._urlencode_utf8({ 'q': text })
  File "/src/mpeds/open_ended_coders.py", line 416, in _urlencode_utf8
    for k, v in params) )
  File "/src/mpeds/open_ended_coders.py", line 416, in <genexpr>
    for k, v in params) )
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 269: ordinal not in range(128)

I don't know what goes wrong here, any ideas?

**Comment by alexhanna** [comment]
Addressed by PR #17
