### ISSUE TITLE
Class probability support for issue and target classifiers 

### ISSUE THREAD

**Issue by erleholgersen** [alexhanna/mpeds#2]
The classifiers used for issue and target do not support probability estimates, while the form classifier does.

**Comment by alexhanna** [comment]
This has to do with the classifiers used. Form uses logistic regression, issue uses SGD, which in sklearn provides a confidence score (http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.SGDClassifier.html#sklearn.linear_model.SGDClassifier.decision_function). Is there a way that this can be converted to a probability estimate?

Target uses a hard voting classifier. This will have to be changed.
