### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by megawattncsu** [alexhanna/mpeds#23]
Hello, 

I am trying to get MPEDS to build but have run into the following error: 

Step 9/14 : RUN pip install -r requirements.txt
 ---> Running in 502a206378d5
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting pandas==0.20.1
  Downloading pandas-0.20.1-cp27-cp27mu-manylinux1_x86_64.whl (22.3 MB)
Collecting numpy==1.12.1
  Downloading numpy-1.12.1-cp27-cp27mu-manylinux1_x86_64.whl (16.5 MB)
Collecting nltk==3.4.5
  Downloading nltk-3.4.5.zip (1.5 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ZsdBu2/nltk/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ZsdBu2/nltk/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-bmdv9S
         cwd: /tmp/pip-install-ZsdBu2/nltk/
    Complete output (1 lines):
    error in nltk setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Service 'mpeds' failed to build : The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1

Would you be able to advise on this? 

Thanks!

**Comment by reuning** [comment]
This looks like an issue with installing nltk, this [StackOverflow might help](https://stackoverflow.com/questions/56371120/issues-setting-up-nltk-within-python-environment).  You probably need to run `pip install -U setuptools` and then try again.

**Comment by megawattncsu** [comment]
Thanks! I'm very new to coding so I apologize for this question but in what program do I run that line? Thanks in advance!

**Comment by megawattncsu** [comment]
I have run the line you gave me and I am still getting the same error.
