### ISSUE TITLE
Warnings when loading vectorizers and classifiers

### ISSUE THREAD

**Issue by erleholgersen** [alexhanna/mpeds#3]
Some of the classifiers and word vectorizers were built in a previous version of scikit-learn, resulting in warnings when they are unpickled using version 0.18.1.

Example: `python example-lexisnexis.py` results in several warnings of the form

`/home/e/eholgersen/.conda/envs/mpeds/lib/python2.7/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator TfidfTransformer from version pre-0.18 when using version 0.18.1. This might lead to breaking code or invalid results. Use at your own risk.`

**Comment by alexhanna** [comment]
Working on regenerating these. The problem is that the new vectorizer and classifier files are too big to fit into GitHub, so I'm attempting to use Git Large File Storage to do this. https://git-lfs.github.com/

**Comment by alexhanna** [comment]
New haystack classifiers added. I also implemented Git LFS. For this, on linstat, you need to add this to your .bashrc

source /opt/rh/rh-git29/enable

after that, you should copy the binary  ~ahanna/public/git-lfs where it can accessed in your path (I have this in ~/bin, and then ~/bin is added into my UNIX path). Inside your local repository copy, type git lfs install. Then you should be able to pull down the new classifiers correctly.

**Comment by erleholgersen** [comment]
Hmm, I could be doing this wrong, but I'm getting a key error when loading the new haystack classifier.

```
>>> execfile('example-lexisnexis.py')
Added 348 articles, skipped 0 abstracts
Loading vectorizer...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "example-lexisnexis.py", line 24, in <module>
    df['y'] = mobj.haystack(df['TEXT'])
  File "mpeds/classify_protest.py", line 111, in haystack
    self.hay_vect = joblib.load('classifiers/haystack-vect_all-source_2017-05-24.pkl')
  File "/home/e/eholgersen/.conda/envs/mpeds/lib/python2.7/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 575, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/home/e/eholgersen/.conda/envs/mpeds/lib/python2.7/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 507, in _unpickle
    obj = unpickler.load()
  File "/home/e/eholgersen/.conda/envs/mpeds/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
KeyError: 'v'
```
 
Any idea what could be causing it?

**Comment by alexhanna** [comment]
I'm getting some SettingWithCopy issues, but can't replicate this. Are you still getting this?

**Comment by erleholgersen** [comment]
Got it working.

**Comment by erleholgersen** [comment]
For future reference, this problem was solved by running `git lfs pull`. See https://github.com/git-lfs/git-lfs/issues/325
