### ISSUE TITLE
SizeCoder extracting years

### ISSUE THREAD

**Issue by erleholgersen** [alexhanna/mpeds#7]
When running the `example-lexisnexis.py `script (on branch [open-ended-coders](alexhanna/mpeds/tree/open-ended-coders/) I noticed that the size coder appears to return years for many of the documents. 

We can consider adding a check to filter out years? Looking at the extracted numbers (without reading the article) it's obvious that 2011, 2015, etc. are years rather than protest sizes, so something as simple as removing all sizes between 2001 and 2017 (say) would probably help.

**Comment by alexhanna** [comment]
Yeah, I think this would be fine to do. Probably excluding all numbers matching 1901-1949, 1951-1999, 2001-2017 would be good.

**Comment by alexhanna** [comment]
Excluded anything that didn't end in 00 in commit 93fe6f3.
